# Font
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 15.0
adjust_line_height  6
adjust_column_width 1
modify_font underline_thickness 150%
modify_font underline_position 10
undercurl_style thick-sparse

# Window
background_opacity 0.4
background_blur 10
dynamic_background_opacity yes
window_padding_width 4
hide_window_decorations no
confirm_os_window_close 0
remember_window_size yes

# Cursor
cursor_shape beam
cursor_beam_thickness 1
selection_background #484f56
selection_foreground none

# Bell
enable_audio_bell no

# Tabs
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
active_tab_font_style bold
inactive_tab_font_style normal
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}


# Misc
editor nvim
