[flavor]
dark = "onedark"
light = ""

[indicator]
parent = { fg = "darkgray" }
current = { fg = "darkgray" }
preview = { fg = "darkgray" }

[mgr]
symlink_target = { italic = false }
border_style = { fg = "darkgray" }
marker_marked = { fg = "#03a9f4" }
marker_cut = { fg = "#e06c75" }
marker_copied = { fg = "#98c379" }
marker_selected = { fg = "#e5c07b" }

count_cut = { fg = "#1e1e2e", bg = "#e06c75" }
count_copied = { fg = "#1e1e2e", bg = "#98c379" }
count_selected = { fg = "#1e1e2e", bg = "#e5c07b" }

[icon]
dirs = [
  { name = ".config", text = "", fg = "#ff9800" },
  { name = ".git", text = "", fg = "#00bcd4" },
  { name = ".github", text = "", fg = "#03a9f4" },
  { name = "documents", text = "", fg = "#00bcd4" },
  { name = "downloads", text = "", fg = "#00bcd4" },
  { name = "music", text = "", fg = "#00bcd4" },
  { name = "pictures", text = "", fg = "#00bcd4" },
  { name = "Documents", text = "", fg = "#00bcd4" },
  { name = "Downloads", text = "", fg = "#00bcd4" },
  { name = "Music", text = "", fg = "#00bcd4" },
  { name = "Pictures", text = "", fg = "#00bcd4" },
]
