# BACKGROUND
background {
    monitor=
    path = ~/pictures/background.jpg
    blur_passes = 0
    contrast = 1
    brightness = 1
    vibrancy = 0
    # contrast = 0.8916
    # brightness = 0.8172
    # vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}



# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, 0.70)
    font_size = 35
    font_family = JetBrainsMono NFP 
    position = 0, 390
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(216, 222, 233, 0.70)
    font_size = 140
    font_family = JetBrainsMono NFP
    position = 0, 250
    halign = center
    valign = center
}

animations {
    enabled = true
    animation = inputFieldColors,0,0,default
}

# INPUT FIELD
input-field {
    monitor =
    size = 550, 100
    outline_thickness = 2
    dots_size = 0.25 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.4 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0)
    font_color = rgba(216, 222, 233, 0.8)
    fade_on_empty = false
    placeholder_text = 
    font_family = JetBrainsMono NFP
    hide_input = false
    position = 0, 0
    halign = center
    valign = center
    check_color = rgba(0, 0, 0, 0)
    fail_color = rgba(0, 0, 0, 0)
    fail_text =
}

label {
    monitor =
    text = 󰐥
    color = rgba(216, 222, 233, 0.9)
    font_size = 35
    font_family = JetBrainsMono NFP
    position = -35, -30
    halign = right
    valign = top
    onclick = systemctl poweroff
}

label {
    monitor =
    text = 󰑓
    color = rgba(216, 222, 233, 0.9)
    font_size = 35
    font_family = JetBrainsMono NFP
    position = -30, -100
    halign = right
    valign = top
    onclick = systemctl reboot
}
